#ifndef SRC_MOTORSCHARACTERSDB_H_
#define SRC_MOTORSCHARACTERSDB_H_

#define MOTOR_SPEED_CONSTANT (6240)
#define SPEED_TO_TORQUE_GRAD (93200)
#define TORQUE_CONST (1.53)
#define MOTOR_GEAR_EFFICIENCY (0.76)
#define MOTOR_EFFICIENCY (0.63 * MOTOR_GEAR_EFFICIENCY)
#define GEAR_RATIO (17.0)
#define INV_GEAR_RATIO (1.0/GEAR_RATIO)
#define POWER_SUPPLY_VOLTAGE (12.0)

// control gains
// TODO - if needed define KI, KP for each motor
#define KI (0.01)
#define KP (0.1)

#endif /* SRC_MOTORSCHARACTERSDB_H_ */
